Query was executed successfully

{x,y} val1
{0,0} 0
{0,1} 1
{1,0} 1
{1,1} 2
{0,2} 2
{0,3} 3
{1,2} 3
{1,3} 4
{0,4} 4
{1,4} 5
{2,0} 2
{2,1} 3
{3,0} 3
{3,1} 4
{2,2} 4
{2,3} 5
{3,2} 5
{3,3} 6
{2,4} 6
{3,4} 7
{4,0} 4
{4,1} 5
{4,2} 6
{4,3} 7
{4,4} 8

Query was executed successfully

{I,J} val
{1,1} 1
{1,2} 0.5
{1,3} 0.333333
{2,1} 0.5
{2,2} 0.333333
{2,3} 0.25
{3,1} 0.333333
{3,2} 0.25
{3,3} 0.2

Query was executed successfully

{x,y} var
{0,0} 5
{0,1} 6
{0,2} 7
{1,0} 6
{1,1} 7
{1,2} 8
{2,0} 7
{2,1} 8
{2,2} 9
{0,3} 8
{0,4} 9
{0,5} 10
{1,3} 9
{1,4} 10
{1,5} 11
{2,3} 10
{2,4} 11
{2,5} 12
{3,0} 8
{3,1} 9
{3,2} 10
{4,0} 9
{4,1} 10
{4,2} 11
{5,0} 10
{5,1} 11
{5,2} 12
{3,3} 11
{3,4} 12
{3,5} 13
{4,3} 12
{4,4} 13
{4,5} 14
{5,3} 13
{5,4} 14
{5,5} 15

Query was executed successfully

{I,J} val
{1,1} 1
{1,2} 0.5
{1,3} 0.333333
{1,4} 0.25
{2,1} 0.5
{2,2} 0.333333
{2,3} 0.25
{2,4} 0.2
{3,1} 0.333333
{3,2} 0.25
{3,3} 0.2
{3,4} 0.166667

{I,J} v
{1,1} 9
{1,2} -36
{1,3} 30
{2,1} -36
{2,2} 192
{2,3} -180
{3,1} 30
{3,2} -180
{3,3} 180

[An error expected at this place for the query "inverse(I1)". And it failed with error code = scidb::SCIDB_SE_EXECUTION::SCIDB_LE_OP_INVERSE_ERROR2. Expected error code = scidb::SCIDB_SE_EXECUTION::SCIDB_LE_OP_INVERSE_ERROR2.]

[An error expected at this place for the query "inverse(I3)". And it failed with error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_OP_INVERSE_ERROR3. Expected error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_OP_INVERSE_ERROR3.]

[An error expected at this place for the query "inverse(I4)". And it failed with error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_OP_INVERSE_ERROR6. Expected error code = scidb::SCIDB_SE_INFER_SCHEMA::SCIDB_LE_OP_INVERSE_ERROR6.]

Query was executed successfully

Query was executed successfully

Query was executed successfully

Query was executed successfully

