Query was executed successfully

[(2),(3),(4),(5),(6)]

[An error expected at this place for the query "select sum(A) from A group by A as part". And it failed with error code = scidb::SCIDB_SE_SYNTAX::SCIDB_LE_ATTRIBUTE_NOT_EXIST. Expected error code = scidb::SCIDB_SE_SYNTAX::SCIDB_LE_ATTRIBUTE_NOT_EXIST.]

Query was executed successfully

